trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'Install Dependencies'

- script: node src/calculateStats.js
  displayName: 'Run Script'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'TestResults'
    artifactName: 'output'
